version: '2'
services:

  web:
    build: .
    ports:
      - "80:8080"
    depends_on:
      - mongo
    networks:
      - all
    environment:
      MONGODB_URI: "mongodb://mongo:27017/test"

  mongo:
    image: mongo
    command: mongod --smallfiles
    networks:
      - all

networks:
  all:
