version: '2'
services:

  web:
    build:
      context: '.'
    ports:
      - "80:8080"
    depends_on:
      - mongo
    networks:
      - all
    links:
      - mongo
    environment:
      MONGODB_URI: ${MONGODB_URI}

  mongo:
    image: mongo
    command: mongod --smallfiles
    networks:
      - all

networks:
  all:
